version: '3.7'

services:
  db:
    image: postgres:11.3-alpine
    # restart: unless-stopped
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./db/user-init.sh:/docker-entrypoint-initdb.d/user-init.sh:ro"

volumes:
  postgres_data: