#!/bin/sh

set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOF
CREATE USER $KR_DB_USER WITH PASSWORD '$KR_DB_PASSWORD';
CREATE DATABASE $KR_DB_DATABASE;
GRANT ALL PRIVILEGES ON DATABASE $KR_DB_DATABASE TO $KR_DB_USER;
EOF
